### ISSUE TITLE
Can anyone help me?

### ISSUE THREAD

**Issue by Unlogisch11** [Rodmg/esptool-gui#10]
I'm trying to flash my ESP8266 Wifi-deauth board for flipper zero using UART. But I keep getting this error: 
![image](https://github.com/user-attachments/assets/dc48b086-0fde-40a6-a930-a9f7511ed74c)

**Comment by Rodmg** [comment]
Hi, did you put your board in bootloader mode before uploading? The ESP8266 will enter the serial bootloader when GPIO0 is held low on reset.

**Comment by Unlogisch11** [comment]
I tried but im not sure how to do it
![image](https://github.com/user-attachments/assets/e04090a5-8a9b-47d2-a3f4-95c559bc7110)
