### ISSUE TITLE
Build from the command line?

### ISSUE THREAD

**Issue by zoobab** [Rodmg/esptool-gui#3]
There is no Makefile, so is there a way to build the binary from the command line?

I know Windows/OSX guys likes to click, but to build software on linux is done one the command line.

**Comment by Rodmg** [comment]
This project is made with Qt and Qt Creator IDE, if you don't want to use the IDE you can use qmake for generating a makefile. More info here: http://doc.qt.io/qt-5/qmake-overview.html

I'm no expert in Qt and haven't tried this method, if there is something missing please feel free to make a pull request.

Thank you for your feedback.
