### ISSUE TITLE
Add support for nodemcu-style upload?

### ISSUE THREAD

**Issue by dalbert2** [Rodmg/esptool-gui#8]
Many platforms use the nodemcu interface that controls entry to the ESP bootloader using DTR and RTS to drive the reset and GPIO0 (boot) pins.  It would be awesome if esptool-gui could support this method.

See: https://tttapa.github.io/ESP8266/Chap06%20-%20Uploading.html

**Comment by Rodmg** [comment]
Hello @dalbert2, That would be handled by the esptool-ck executable we are bundling with the GUI, it should be just a matter of adding a parameter to the command line we are calling in doUpload() and doTest() on mainwindow.cpp, If you or someone could help me with a PR that would be great. If not I could look into that when I have some free time.

**Comment by epiller** [comment]
Any updates on this? Would be awesome to have this feature!

**Comment by erfindungsbureau** [comment]
I would also be very interested in this feature
